name: Installer

on: 
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write

jobs:
  installer:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: ['3.3.4']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Create Core Lich-5 package
        id: install_core_scripts
        run: |
          mkdir Lich5
          mkdir Lich5/data
          mkdir Lich5/scripts
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/alias.lic > lich5/scripts/alias.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/autostart.lic > lich5/scripts/autostart.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/ewaggle.lic > lich5/scripts/ewaggle.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/go2.lic > lich5/scripts/go2.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/jinx.lic > lich5/scripts/jinx.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/lich5-update.lic > lich5/scripts/lich5-update.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/log.lic > lich5/scripts/log.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/map.lic > lich5/scripts/map.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/repository.lic > lich5/scripts/repository.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/vars.lic > lich5/scripts/vars.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/version.lic > lich5/scripts/version.lic
          curl https://raw.githubusercontent.com/rpherbig/dr-scripts/master/dependency.lic > lich5/scripts/dependency.lic
          curl https://raw.githubusercontent.com/elanthia-online/scripts/master/scripts/effect-list.xml > lich5/data/effect-list.xml
          cp lich.rbw Lich5/
          cp -r lib Lich5/
          gem install activesupport ascii_charts concurrent-ruby curses ftools gtk3 json jwt mechanize nokogiri redis sequel sqlite3 terminal-table tomlib tzinfo tzinfo-data webrick xmpp4r --no-document
          rm -r -fo C:\msys64\ucrt64\share\man\*
          rm -r -fo C:\msys64\usr\share\man\*
          rm -r -fo C:\msys64\var\cache\pacman\pkg\*
          iscc "R4LGTK3.iss"
          mv .\Output\Ruby4Lich5.exe .\Ruby4Lich5.exe
      - name: Add to Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          files: |
            Ruby4Lich5.exe
