name: Rubocop
on: 
  push:
    branches:
      - master
      - staging
      - main
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"
  pull_request:
    paths:
      - "**/*.lic"
      - "**/*.rb"
      - "lich.rbw"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    strategy:
      matrix:
        ruby: ['4.0']
    name: Run Rubocop on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      
      - uses: ruby/setup-ruby@b90be12699fdfcbee4440c2bba85f6f460446bb0 # v1.279.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Rubocop
        run: |
          bundle exec rubocop
